###
GET http://localhost/api/users

###

POST http://localhost/api/users
Content-Type: application/json

{"inputs":[{
    "id":2,
    "name":"abc",
    "age":16,
    "count":true,
    "marks":100
},{
    "id":3,
    "name":"def",
    "age":18,
    "count":true,
    "marks":100 
}]
}
###

DELETE http://localhost:6001/users


### 
PUT http://localhost:6001/users
Content-Type: application/json

{"inputs":[{
    "id":1,
    "name":"abc",
    "age":16,
    "count":true
}
]
}


###
POST http://localhost:5000/api/stores
Content-Type: application/json

{
    "name":"store"
}

###

GET http://localhost:5000/api/stores


###
POST http://localhost/api/users
Content-Type: application/json

{"inputs":{
    "id":[1,2],
    "name":["abc","def"],
    "age":[16,17],
    "count":[true,false],
    "marks":[100,200]
}
}