###
GET http://localhost:6000/users

###

POST http://localhost:6000/users
Content-Type: application/json

{"inputs":[{
    "name":"test name 1",
    "age":16,
    "count":true
},
{
    "name":"test name 2",
    "age":26,
    "count":false
},
{
    "name":"test name 3",
    "age":36,
    "count":true
},
{
    "name":"test name 4",
    "age":66,
    "count":false
}]
}
###

DELETE http://localhost:6000/users