###
GET http://localhost:6001/users

###

POST http://localhost:6001/users
Content-Type: application/json

{"inputs":[{
    "id":2,
    "name":"Vivek udpate",
    "age":16,
    "count":true
}]
}
###

DELETE http://localhost:6001/users


### 
PUT http://localhost:6001/users
Content-Type: application/json

{"inputs":[{
    "id":1,
    "name":"SIMON UPDATE 2",
    "age":16,
    "count":true
}
]
}